[theme]
primaryColor = "#1E88E5"    # Customize the primary color (blue in this case)
backgroundColor = "#F5F5F5" # Set a light gray background color
secondaryBackgroundColor = "#FFFFFF" # Set a white sidebar background
textColor = "#262730"       # Customize text color
font = "sans serif"         # Choose font style

[global]
page_title = "Recipe Manager"  # Set the app's page title
page_icon = "🍴"              # Add a favicon (use an emoji or a URL)
layout = "centered"           # Options: "centered" or "wide"
