[theme]
primaryColor = "#1E88E5"    # Customize the primary color (blue in this case)
backgroundColor = "#000000" 
secondaryBackgroundColor = "#000000" # Set a white sidebar background
textColor = "#F5F5F5"       # Customize text color
font = "sans serif"         # Choose font style

